theme: jekyll-theme-cayman
title: "Fleeper Library"
description: "Flepper is a library to facilitate some database interactions that we need to perform in our applications. The initial idea of Flepper is to provide a query builder for writing SQL queries fluently, improving the readability of your code"
layout: "flepper-site"